project:
  type: website

website:
  title: "arieknoester.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.pdf
        text: Resume

format:
  html:
    theme: flatly
    page-layout: full
    css: styles.css
    toc: false



